// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcrAFGQ7mmnbIJwVmvjY___SVBv5pWfQ',
    appId: '1:903194290505:web:63f54263a5e28274d35298',
    messagingSenderId: '903194290505',
    projectId: 'dieter-86c40',
    authDomain: 'dieter-86c40.firebaseapp.com',
    storageBucket: 'dieter-86c40.appspot.com',
    measurementId: 'G-YF3X2MMRCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDprlrGG2FruP4h7_PPNXPo_Vb1kc_myjI',
    appId: '1:903194290505:android:0706f338044e301ad35298',
    messagingSenderId: '903194290505',
    projectId: 'dieter-86c40',
    storageBucket: 'dieter-86c40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfw-4eG9FTePHEuFCKE8jlvHOGD8NlvqI',
    appId: '1:903194290505:ios:786e4ad004ffc68fd35298',
    messagingSenderId: '903194290505',
    projectId: 'dieter-86c40',
    storageBucket: 'dieter-86c40.appspot.com',
    iosBundleId: 'com.example.dieter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfw-4eG9FTePHEuFCKE8jlvHOGD8NlvqI',
    appId: '1:903194290505:ios:786e4ad004ffc68fd35298',
    messagingSenderId: '903194290505',
    projectId: 'dieter-86c40',
    storageBucket: 'dieter-86c40.appspot.com',
    iosBundleId: 'com.example.dieter',
  );
}
